// Reconcile: Group Travel intake sheet  →  LIVE GROUP MASTERSHEET
//
// Why this exists: the website form (/api/submit) mirrors a submission to the
// master at submission time, but the GROUP ID is generated by a Smartsheet
// formula on the intake sheet AFTER the row lands — so the form can't carry it.
// The master's Group IDs are populated by a separate automation; if that
// automation ever misses a row (as happened with Monster Energy / VQ9GMONAUG26),
// the group is in the intake sheet but never reaches the master.
//
// This endpoint closes that gap: it lists every intake group that isn't in the
// master and (on commit) creates it. Columns are resolved BY TITLE on both
// sheets so a column-ID change can never write to the wrong field.
//
// A group is only ever created ONCE: after it has been seen on the master its intake row is ticked
// 'Synced to Master' and skipped from then on, so archived/deleted master rows stay gone.
//
// Usage (on Vercel, where SMARTSHEET_API_TOKEN is set):
//   GET /api/reconcile-groups?setup=1            → DRY RUN of the one-time setup (adds the checkbox column, ticks existing rows)
//   GET /api/reconcile-groups?setup=1&commit=1   → does it
//   GET /api/reconcile-groups            → DRY RUN: reports what's missing, writes nothing
//   GET /api/reconcile-groups?commit=1   → creates the missing master rows

const INTAKE_SHEET = '3569349083221892';   // Group Travel intake sheet
const MASTER_SHEET = '4820086761148292';   // LIVE GROUP MASTERSHEET

// candidate titles (case-insensitive) for each logical field, per sheet
const INTAKE_TITLES = {
  groupId:      ['Group ID'],
  company:      ['Company Name'],
  contactName:  ['Event Manager / Contact Name', 'Event Manager/Contact Name', 'Contact Name', 'Event Manager'],
  contactEmail: ['Event Manager Email', 'Event Manager E-mail', 'Contact Email', 'Contact E-mail'],
  contactPhone: ['Event Manager Contact Number', 'Event Manager Phone', 'Contact Phone', 'Contact Number'],
  startDate:    ['Arrival Date', 'Travel Start Date', 'Start Date'],
  endDate:      ['Departure Date', 'Travel End Date', 'End Date'],
  doNotSync:    ['Do Not Sync', 'Archived', 'Do Not Re-Sync', 'Skip Sync'],
  // Checkbox this endpoint maintains itself: ticked once a group has been on the master. A ticked row is
  // NEVER re-created, so archiving/deleting a group off the master sticks (2026-10-02, Vera: archived rows
  // came back every morning because this cron rebuilt them from the intake sheet).
  synced:       ['Synced to Master'],
};
const MASTER_TITLES = {
  groupId:      ['GROUP ID', 'Group ID'],
  company:      ['Company Name'],
  contactName:  ['Contact Name'],
  contactEmail: ['Contact E-mail', 'Contact Email'],
  contactPhone: ['Contact Phone', 'Contact Number'],
  status:       ['Status'],
  completed:    ['Completed'],
  startDate:    ['Travel Start Date', 'Start Date'],
  endDate:      ['Travel End Date', 'End Date'],
  autoSynced:   ['Auto-Synced', 'Auto Synced'],
};

export default async function handler(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
  if (req.method === 'OPTIONS') return res.status(200).end();

  const TOKEN = process.env.SMARTSHEET_API_TOKEN;
  if (!TOKEN) return res.status(500).json({ error: 'Missing SMARTSHEET_API_TOKEN' });
  const commit = req.query?.commit === '1' || req.body?.commit === true;

  const api = (path, opts = {}) =>
    fetch(`https://api.smartsheet.com/2.0${path}`, {
      ...opts,
      headers: { Authorization: `Bearer ${TOKEN}`, 'Content-Type': 'application/json', ...opts.headers },
    }).then(r => r.json());

  const ZWSP = /​/g;
  const norm = v => (v == null ? '' : String(v)).replace(ZWSP, '').trim();
  const cellVal = (row, colId) => {
    const c = row.cells?.find(c => c.columnId === colId);
    return c?.value ?? c?.displayValue ?? null;
  };
  const resolve = (sheet, titleMap) => {
    const byTitle = {};
    for (const c of sheet.columns) byTitle[c.title.trim().toLowerCase()] = c.id;
    const out = {};
    for (const [field, candidates] of Object.entries(titleMap)) {
      for (const t of candidates) { const id = byTitle[t.trim().toLowerCase()]; if (id) { out[field] = id; break; } }
    }
    return out;
  };

  // ── Status self-heal (Vera 2026-07-08) ────────────────────────────────────
  // The GROUPS dashboard report only shows rows that have a Status; manually
  // added groups arrive with a blank one and silently vanish from the widget.
  // Fix: any master row with a GROUP ID but no Status gets 'New'. Runs (a)
  // instantly via a Smartsheet webhook on the master (register once with
  // ?registerHook=1), (b) on the daily cron, (c) on any manual run.
  async function backfillStatus() {
    const master = await api(`/sheets/${MASTER_SHEET}`);
    if (master.error || !master.columns) return { backfillError: 'could not read master' };
    const M = resolve(master, MASTER_TITLES);
    if (!M.groupId || !M.status) return { backfillError: 'missing GROUP ID / Status column' };
    const fixes = (master.rows || [])
      .filter(r => norm(cellVal(r, M.groupId)) && !norm(cellVal(r, M.status)))
      .map(r => ({ id: r.id, cells: [{ columnId: M.status, value: 'New' }] }));
    if (fixes.length) await api(`/sheets/${MASTER_SHEET}/rows`, { method: 'PUT', body: JSON.stringify(fixes) });
    return { statusBackfilled: fixes.length };
  }

  // ── Duplicate self-heal (2026-07-09, widened 2026-08-27) ──────────────────
  // A Smartsheet "Copy row" workflow (invisible to the automationrules API)
  // copies rows back onto the master: manager types a group on the master →
  // sync-groups mirrors it to the Agent sheet → the workflow copies it back →
  // the master shows the group twice (seen with SY90CANOCT26YYC, created by
  // automation@smartsheet.com 61s after the manual row). Until that workflow
  // is deleted in the UI, this removes any master row whose GROUP ID
  // duplicates an OLDER row.
  //
  // Originally this only deleted duplicates created by
  // automation@smartsheet.com specifically, to avoid ever touching a manual
  // row. Widened 2026-08-27 (Vera reported SY90CANSEP26/SY90CANOCT26 each
  // tripled on the master) after confirming the creator-based guard is no
  // longer the right check: a Group ID is a unique key by design -- two rows
  // sharing one is always an error regardless of who/what created the extra
  // copy, and the "Copy row" workflow's rows aren't reliably attributed to
  // automation@smartsheet.com anymore. Now always keeps the OLDEST row for a
  // given Group ID and deletes every newer one, no creator check.
  async function dedupeMaster() {
    const master = await api(`/sheets/${MASTER_SHEET}?include=writerInfo`);
    if (master.error || !master.columns) return { dedupeError: 'could not read master' };
    const M = resolve(master, MASTER_TITLES);
    if (!M.groupId) return { dedupeError: 'missing GROUP ID column' };
    const byGid = new Map();
    for (const row of master.rows || []) {
      const gid = norm(cellVal(row, M.groupId)).toLowerCase();
      if (!gid) continue;
      if (!byGid.has(gid)) byGid.set(gid, []);
      byGid.get(gid).push(row);
    }
    const toDelete = [];
    for (const [gid, rows] of byGid) {
      if (rows.length < 2) continue;
      rows.sort((a, b) => new Date(a.createdAt) - new Date(b.createdAt));
      for (const row of rows.slice(1)) {
        toDelete.push({ id: row.id, gid });
      }
    }
    if (toDelete.length) {
      await api(`/sheets/${MASTER_SHEET}/rows?ids=${toDelete.map(d => d.id).join(',')}`, { method: 'DELETE' });
    }
    return { duplicatesDeleted: toDelete.length, duplicateGids: toDelete.map(d => d.gid) };
  }

  // ── Arbonne NVPLM sync (2026-10-07) ───────────────────────────────────────
  // Arbonne's Smartsheet "Flights US/CA NVPLM 2027 Maui Trip" -> our "2. ENVOY Traveller MasterSheet".
  // Rule (Vera/Jos): ONLY rows whose "NVP Approved by Arbonne" = YES are copied. Their data flows to us; our Agent Notes /
  // Agent Assigned flow back to their "Notes From Travel Edge" / "Travel Edge Team Member". Their Status is ignored.
  // Matching is by column TITLE (never column ids). Each synced row is keyed by "Arbonne Row ID" on our sheet, so a row
  // is created once and then updated in place. Manual run: ?arbonne=1 (dry run) / ?arbonne=1&commit=1.
  // Webhooks + the daily cron only run it when ARB_ENABLED is true.
  const ARB_SHEET = '4224539799277444';
  const ENVOY_SHEET = '8780932377956228';
  const ARB_ENABLED = false;               // flip to true once the Group ID question is settled and a live test passed
  const ARB_DEFAULT_GROUP_ID = '';         // used when Arbonne's sheet has no (or a blank) "Group ID" column
  const ARB_SOURCE = 'Arbonne NVPLM 2027';
  const ARB_THEM_TO_US = [
    ['Notes from Arbonne', 'Client Notes'], ['Consultant ID #', 'Expense Account/Employee Id'], ['Email Address', 'Email'],
    ['On-Site Phone Number', 'Phone Number'], ['Departure City or Airport', 'Departure Airport'], ['Arrival Date', 'Departure Date'],
    ['Date of Return', 'Return Date'], ['Preferred Departure Time', 'Departure Time'], ['Preferred Return Time', 'Return Time'],
    ['Seat Preference', 'Seat Preference'], ['Preferred Airline', 'Airline Preference 1'],
    ['NVP First Name', 'First Name'], ['NVP Middle Name', 'Middle Name'], ['NVP Last Name', 'Last Name'], ['NVP Date of Birth', 'Date of Birth'],
    ['NVP Gender', 'Gender'], ['NVP Citizenship', 'Nationality'], ['NVP KTN/PASS ID', 'Global Entry Number'],
    ["Guest's First Name", 'Guest First Name'], ["Guest's Middle Name", 'Guest Middle Name'], ["Guest's Last Name", 'Guest Last Name'],
    ["Guest's Date of Birth", 'Guest DOB'], ["Guest's Gender", 'Guest Gender'], ['Guest KTN/PASS ID', 'Guest TSA Number'], ['Guest Citizenship', 'Guest Passport Nationality'],
    // approval columns Vera asked us to add "the way it's written on theirs"
    ['NVP Approved by Arbonne', 'NVP Approved by Arbonne'], ['Guest Approved by Arbonne', 'Guest Approved by Arbonne'],
    ['Did you achieve a guest?', 'Did you achieve a guest?'], ['Assistance with flight booking? (Unearned guest)', 'Assistance with flight booking? (Unearned guest)'],
  ];
  const ARB_US_TO_THEM = [['Agent Notes', 'Notes From Travel Edge'], ['Agent Assigned:', 'Travel Edge Team Member'], ['In progress', 'In Progress'], ['Completed', 'Completed']];
  const ARB_NEW_COLS = [
    { title: 'NVP Approved by Arbonne', type: 'PICKLIST', options: ['YES', 'NO', 'HOLD', 'Duplicate'] },
    { title: 'Guest Approved by Arbonne', type: 'PICKLIST', options: ['YES', 'NO', 'HOLD', 'Duplicate'] },
    { title: 'Did you achieve a guest?', type: 'PICKLIST', options: ['Yes', 'No'] },
    { title: 'Assistance with flight booking? (Unearned guest)', type: 'PICKLIST', options: ['Yes', 'No'] },
    { title: 'Client Notes', type: 'TEXT_NUMBER' },
    { title: 'Arbonne Row ID', type: 'TEXT_NUMBER' },
  ];
  const tkey = s => String(s == null ? '' : s).toLowerCase().replace(/[‘’'`]/g, '').replace(/\s+/g, ' ').trim();
  const byTitle = sheet => { const m = {}; for (const c of sheet.columns || []) m[tkey(c.title)] = c; return m; };
  const rawVal = (row, colId) => { const c = row.cells?.find(c => c.columnId === colId); if (!c) return ''; const isContact = c.displayValue && /@/.test(String(c.value || '')); const v = isContact ? c.displayValue : (c.value != null ? c.value : c.displayValue); return v == null ? '' : String(v).replace(ZWSP, '').trim(); };

  async function arbonneSync(commit) {
    const w = async (method, path, body) => {
      const r = await fetch(`https://api.smartsheet.com/2.0${path}`, { method, headers: { Authorization: `Bearer ${TOKEN}`, 'Content-Type': 'application/json' }, body: JSON.stringify(body) });
      const j = await r.json();
      if (!r.ok || (j.message && j.message !== 'SUCCESS')) throw new Error(`Smartsheet ${method} ${path}: ${j.message || r.status}`);
      return j;
    };
    const out = { dryRun: !commit };
    const [theirs, ours0] = await Promise.all([api(`/sheets/${ARB_SHEET}`), api(`/sheets/${ENVOY_SHEET}`)]);
    if (theirs.error || !theirs.columns) throw new Error('Cannot read Arbonne sheet: ' + (theirs.message || theirs.errorCode));
    if (ours0.error || !ours0.columns) throw new Error('Cannot read Envoy master: ' + (ours0.message || ours0.errorCode));
    let ours = ours0, O = byTitle(ours), T = byTitle(theirs);

    // 1) make sure the new columns exist on our sheet
    const missingCols = ARB_NEW_COLS.filter(c => !O[tkey(c.title)]);
    out.columnsToAdd = missingCols.map(c => c.title);
    if (missingCols.length && commit) {
      await w('POST', `/sheets/${ENVOY_SHEET}/columns`, missingCols.map(c => ({ title: c.title, type: c.type, index: ours.columns.length, ...(c.options ? { options: c.options } : {}) })));
      ours = await api(`/sheets/${ENVOY_SHEET}`); O = byTitle(ours);
      out.columnsAdded = missingCols.length;
    }
    const need = n => O[tkey(n)];
    const keyCol = need('Arbonne Row ID');

    // 2) resolve the mappings (report anything that cannot be matched)
    const pairs = [], unmatched = [];
    for (const [t, u] of ARB_THEM_TO_US) { const tc = T[tkey(t)], uc = O[tkey(u)]; if (tc && uc) pairs.push({ t, u, tc, uc }); else unmatched.push(`${t} -> ${u}${!tc ? ' (their column missing)' : ''}${!uc ? ' (our column missing)' : ''}`); }
    const back = [];
    for (const [u, t] of ARB_US_TO_THEM) { const uc = O[tkey(u)], tc = T[tkey(t)]; if (uc && tc) back.push({ u, t, uc, tc }); else unmatched.push(`${u} -> ${t} (back-sync column missing)`); }
    out.unmatchedMappings = unmatched;
    const approvedCol = T[tkey('NVP Approved by Arbonne')], theirGroupCol = T[tkey('Group ID')];
    if (!approvedCol) throw new Error('Their "NVP Approved by Arbonne" column not found');

    // 3) our existing rows keyed by Arbonne Row ID
    const byKey = new Map();
    if (keyCol) for (const r of ours.rows || []) { const k = rawVal(r, keyCol.id); if (k) byKey.set(k, r); }

    const sc = id => ours.columns.find(c => c.id === id);
    const today = new Date().toISOString().slice(0, 10);
    const toCreate = [], toUpdate = [], backUpdates = [], skipped = [];
    for (const tr of theirs.rows || []) {
      const key = 'ARB-' + tr.id;
      const approved = tkey(rawVal(tr, approvedCol.id)) === 'yes';
      const existing = byKey.get(key);
      const name = rawVal(tr, (T[tkey('Consultant Name')] || {}).id);
      if (!approved && !existing) { skipped.push({ row: tr.rowNumber, reason: 'not approved (YES)' }); continue; }

      if (!approved && existing) {   // was copied before, no longer YES: only keep the approval columns current
        const cells = [];
        for (const p of pairs.filter(p => /Approved by Arbonne$/.test(p.u))) { const nv = rawVal(tr, p.tc.id); if (nv !== rawVal(existing, p.uc.id)) cells.push({ columnId: p.uc.id, value: nv }); }
        if (cells.length) toUpdate.push({ id: existing.id, cells, row: tr.rowNumber });
        continue;
      }
      const gid = String((theirGroupCol && rawVal(tr, theirGroupCol.id)) || ARB_DEFAULT_GROUP_ID).trim().split(/[\s=]/)[0];   // dropdown may read 'MLTIARBJAN27OGGC = Canadian'
      if (!existing && !gid) out.noGroupId = (out.noGroupId || 0) + 1;   // still copied; Group ID stays blank until Arbonne supplies one

      if (!existing) {
        const cells = [];
        for (const p of pairs) { const v = rawVal(tr, p.tc.id); if (v !== '') cells.push({ columnId: p.uc.id, value: v }); }
        const add = (title, value) => { const c = O[tkey(title)]; if (c && value !== '') cells.push({ columnId: c.id, value }); };
        add('Group ID', gid); add('Source', ARB_SOURCE); add('Traveller Type', 'Invitee'); add('Company Name', 'Arbonne'); add('Submission Date', today);
        if (keyCol) cells.push({ columnId: keyCol.id, value: key });
        toCreate.push({ toBottom: true, cells, row: tr.rowNumber, name });
      } else {
        const cells = [];   // update only what changed; never blank out something Arbonne left empty
        for (const p of pairs) {
          const v = rawVal(tr, p.tc.id), cur = rawVal(existing, p.uc.id);
          if (v !== '' && v !== cur) cells.push({ columnId: p.uc.id, value: v });
        }
        const gcol = O[tkey('Group ID')];
        if (gcol && gid && gid !== rawVal(existing, gcol.id)) cells.push({ columnId: gcol.id, value: gid });
        if (cells.length) toUpdate.push({ id: existing.id, cells, row: tr.rowNumber });
      }
      // our -> theirs
      if (existing) {
        const bc = [];
        for (const b of back) {
          if (b.tc.type === 'CHECKBOX') { const v = rawVal(existing, b.uc.id) === 'true', cur = rawVal(tr, b.tc.id) === 'true'; if (v !== cur) bc.push({ columnId: b.tc.id, value: v }); continue; }
          const v = rawVal(existing, b.uc.id), cur = rawVal(tr, b.tc.id); if (v !== cur) bc.push({ columnId: b.tc.id, value: v });
        }
        if (bc.length) backUpdates.push({ id: tr.id, cells: bc, row: tr.rowNumber });
      }
    }
    out.approvalValues = {}; for (const tr of theirs.rows || []) { const v = rawVal(tr, approvedCol.id) || '(blank)'; out.approvalValues[v] = (out.approvalValues[v] || 0) + 1; }
    out.alreadyCopied = byKey.size;
    out.approvedNew = toCreate.length; out.rowsToUpdate = toUpdate.length; out.backSyncRows = backUpdates.length;
    out.skipped = skipped.length; out.skippedDetail = skipped;
    out.plannedNewRows = toCreate.map(c => ({ theirRow: c.row, fields: c.cells.length }));
    if (!commit) return out;

    if (toCreate.length) { const res = await w('POST', `/sheets/${ENVOY_SHEET}/rows`, toCreate.map(({ toBottom, cells }) => ({ toBottom, cells }))); out.created = (res.result || []).length; }
    if (toUpdate.length) { await w('PUT', `/sheets/${ENVOY_SHEET}/rows`, toUpdate.map(({ id, cells }) => ({ id, cells }))); out.updated = toUpdate.length; }
    if (backUpdates.length) { await w('PUT', `/sheets/${ARB_SHEET}/rows`, backUpdates.map(({ id, cells }) => ({ id, cells }))); out.backSynced = backUpdates.length; }
    return out;
  }

  if (req.query?.arbonne === '1') {
    try { return res.status(200).json(await arbonneSync(commit)); } catch (err) { return res.status(500).json({ error: err.message }); }
  }

  // TEMPORARY (Arbonne test, 2026-10-07): ?arbonneTest=1 fills in the TEST data on their row 8 and its Envoy copy so both
  // sync directions can be checked. Hard-wired to those two rows only. REMOVE right after the test.
  if (req.query?.arbonneTest === '1') {
    try {
      const [theirs, ours] = await Promise.all([api(`/sheets/${ARB_SHEET}`), api(`/sheets/${ENVOY_SHEET}`)]);
      const T = byTitle(theirs), O = byTitle(ours);
      const tr = (theirs.rows || []).find(r => r.rowNumber === 8);
      if (!tr) return res.status(200).json({ error: 'their row 8 not found' });
      const keyCol = O[tkey('Arbonne Row ID')];
      const orow = (ours.rows || []).find(r => rawVal(r, keyCol.id) === 'ARB-' + tr.id);
      if (!orow) return res.status(200).json({ error: 'Envoy copy of their row 8 not found (is it approved + synced?)' });
      const put = async (sheet, body) => { const r = await fetch(`https://api.smartsheet.com/2.0/sheets/${sheet}/rows`, { method: 'PUT', headers: { Authorization: `Bearer ${TOKEN}`, 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); const j = await r.json(); return { ok: r.ok && (!j.message || j.message === 'SUCCESS'), message: j.message }; };
      const a = await put(ARB_SHEET, [{ id: tr.id, cells: [{ columnId: T[tkey('Group ID')].id, value: 'MLTIARBJAN27OGGU (US)' }, { columnId: T[tkey('NVP Approved by Arbonne')].id, value: 'YES' }] }]);
      const b = await put(ENVOY_SHEET, [{ id: orow.id, cells: [
        { columnId: O[tkey('Agent Notes')].id, value: 'TEST NOTE from Kensington agent (sync test)' },
        { columnId: O[tkey('Agent Assigned:')].id, objectValue: { objectType: 'CONTACT', email: 'nehman.rahimi@kensingtoncorporate.com', name: 'Nehman Rahimi' } },
        { columnId: O[tkey('In progress')].id, value: true },
      ] }]);
      return res.status(200).json({ theirGroupId: a, envoyAgentFields: b });
    } catch (err) { return res.status(500).json({ error: err.message }); }
  }

  // One-time: GET ?arbonneHooks=1 registers webhooks on Arbonne's sheet (their edits) and on the Envoy master (agent notes/assignment).
  if (req.query?.arbonneHooks === '1') {
    try {
      const hooks = await api(`/webhooks?includeAll=true`);
      const out = [];
      for (const [name, sid] of [['Arbonne NVPLM sync (their sheet)', ARB_SHEET], ['Arbonne NVPLM sync (Envoy master)', ENVOY_SHEET]]) {
        let hook = (hooks.data || []).find(h => String(h.scopeObjectId) === sid && (h.callbackUrl || '').includes('/api/reconcile-groups'));
        if (!hook) {
          const cr = await api(`/webhooks`, { method: 'POST', body: JSON.stringify({ name, callbackUrl: 'https://kensington-group-form.vercel.app/api/reconcile-groups', scope: 'sheet', scopeObjectId: Number(sid), events: ['*.*'], version: 1 }) });
          hook = cr.result;
          if (!hook) { out.push({ sheet: sid, error: cr.message || 'create failed' }); continue; }
        }
        const en = hook.enabled ? { result: hook } : await api(`/webhooks/${hook.id}`, { method: 'PUT', body: JSON.stringify({ enabled: true }) });
        out.push({ sheet: sid, id: hook.id, enabled: en.result?.enabled ?? hook.enabled, status: en.result?.status ?? hook.status });
      }
      return res.status(200).json({ ok: true, webhooks: out });
    } catch (err) { return res.status(500).json({ error: err.message }); }
  }

  // TEMPORARY read-only discovery (Arbonne project, 2026-10-07): ?peek=list&name=<text> lists sheets this token can
  // see; ?peek=<sheetId> returns that sheet's column layout. Names / counts only -- NO row data. Remove after use.
  if (req.query?.peek) {
    try {
      const q = String(req.query.peek);
      const me = await api('/users/me');
      const out = { tokenOwner: { email: me.email, name: [me.firstName, me.lastName].filter(Boolean).join(' ') } };
      if (q === 'list') {
        const needle = String(req.query.name || '').toLowerCase();
        const all = await api('/sheets?includeAll=true');
        out.sheets = (all.data || []).filter(s => !needle || (s.name || '').toLowerCase().includes(needle))
          .map(s => ({ id: s.id, name: s.name, accessLevel: s.accessLevel, permalink: s.permalink }));
        return res.status(200).json(out);
      }
      const sh = await api(`/sheets/${q}?pageSize=1`);
      if (sh.errorCode) return res.status(200).json({ ...out, error: sh.errorCode, message: sh.message });
      out.sheet = { id: sh.id, name: sh.name, accessLevel: sh.accessLevel, totalRowCount: sh.totalRowCount, permalink: sh.permalink,
        columns: (sh.columns || []).map(c => ({ id: c.id, title: c.title, type: c.type, primary: !!c.primary, options: c.options, formula: !!c.formula, locked: !!c.locked })) };
      return res.status(200).json(out);
    } catch (err) { return res.status(500).json({ error: err.message }); }
  }

  // Smartsheet webhook verification challenge — echo it.
  const hookChallenge = req.headers['smartsheet-hook-challenge'];
  if (hookChallenge) {
    res.setHeader('Smartsheet-Hook-Response', hookChallenge);
    return res.status(200).json({ smartsheetHookResponse: hookChallenge });
  }

  // Smartsheet webhook change event on the master → self-heal right now.
  // (The backfill's own PUT re-fires the webhook once; the second pass finds
  // nothing blank and writes nothing, so it converges immediately.)
  const pbody = typeof req.body === 'string' ? (() => { try { return JSON.parse(req.body); } catch { return {}; } })() : (req.body || {});
  if (req.method === 'POST' && Array.isArray(pbody.events)) {
    const scope = String(pbody.scopeObjectId || '');
    if (scope === ARB_SHEET || scope === ENVOY_SHEET) {      // Arbonne sync webhooks (always answer 200 so Smartsheet never disables the hook)
      if (!ARB_ENABLED) return res.status(200).json({ ok: true, arbonne: 'disabled' });
      try { return res.status(200).json({ ok: true, ...(await arbonneSync(true)) }); } catch (e) { return res.status(200).json({ ok: true, error: e.message }); }
    }
    const out = await backfillStatus();
    const dd = await dedupeMaster();
    return res.status(200).json({ ok: true, ...out, ...dd });
  }

  // One-time self-registration of that webhook: GET ?registerHook=1
  if (req.query?.registerHook === '1') {
    const hooks = await api(`/webhooks?includeAll=true`);
    let hook = (hooks.data || []).find(h => String(h.scopeObjectId) === MASTER_SHEET && (h.callbackUrl || '').includes('/api/reconcile-groups'));
    if (!hook) {
      const cr = await api(`/webhooks`, { method: 'POST', body: JSON.stringify({ name: 'Groups status self-heal', callbackUrl: 'https://kensington-group-form.vercel.app/api/reconcile-groups', scope: 'sheet', scopeObjectId: Number(MASTER_SHEET), events: ['*.*'], version: 1 }) });
      hook = cr.result;
      if (!hook) return res.status(502).json({ error: 'webhook create failed', detail: cr });
    }
    const en = hook.enabled ? { result: hook } : await api(`/webhooks/${hook.id}`, { method: 'PUT', body: JSON.stringify({ enabled: true }) });
    const bf = await backfillStatus();
    return res.status(200).json({ ok: true, webhook: { id: hook.id, enabled: en.result?.enabled ?? hook.enabled, status: en.result?.status ?? hook.status }, ...bf });
  }

  // One-time setup: add the 'Synced to Master' checkbox column to the intake sheet and tick every intake row that
  // is older than 12h (those have all had a daily cron pass already, so they must never be re-created).
  if (req.query?.setup === '1') {
    try {
      let intake = await api(`/sheets/${INTAKE_SHEET}`);
      if (intake.error || !intake.columns) return res.status(502).json({ error: 'Could not read intake sheet', detail: intake });
      let I = resolve(intake, INTAKE_TITLES);
      const out = { dryRun: !commit, columnExisted: !!I.synced };
      if (!I.synced && commit) {
        const cr = await api(`/sheets/${INTAKE_SHEET}/columns`, { method: 'POST', body: JSON.stringify({ title: 'Synced to Master', type: 'CHECKBOX', index: intake.columns.length }) });
        if (!cr.result) return res.status(502).json({ error: 'Could not add column', detail: cr });
        intake = await api(`/sheets/${INTAKE_SHEET}`);
        I = resolve(intake, INTAKE_TITLES);
      }
      const cutoff = Date.now() - 12 * 3600 * 1000;
      const toTick = (intake.rows || []).filter(row => {
        const gid = norm(cellVal(row, I.groupId));
        if (!gid || /^(quote only|quote|n\/?a|tbd|none|pending|test)$/i.test(gid)) return false;
        if (I.synced && cellVal(row, I.synced) === true) return false;
        return new Date(row.createdAt).getTime() < cutoff;
      });
      out.rowsToTick = toTick.length;
      out.groups = toTick.map(row => norm(cellVal(row, I.groupId)));
      if (commit && I.synced) {
        for (let i = 0; i < toTick.length; i += 100) {
          const batch = toTick.slice(i, i + 100).map(row => ({ id: row.id, cells: [{ columnId: I.synced, value: true }] }));
          const w = await api(`/sheets/${INTAKE_SHEET}/rows`, { method: 'PUT', body: JSON.stringify(batch) });
          if (w.message && w.message !== 'SUCCESS') return res.status(502).json({ error: 'Tick failed', detail: w, ...out });
        }
        out.ticked = toTick.length;
      }
      return res.status(200).json(out);
    } catch (err) {
      return res.status(500).json({ error: err.message });
    }
  }

  if (ARB_ENABLED && commit) { try { await arbonneSync(true); } catch (e) { console.error('arbonne cron sync failed', e.message); } }

  try {
    const heal = await backfillStatus();
    const dd = await dedupeMaster();
    Object.assign(heal, dd);
    const [intake, master] = await Promise.all([api(`/sheets/${INTAKE_SHEET}`), api(`/sheets/${MASTER_SHEET}`)]);
    if (intake.error || !intake.columns) return res.status(502).json({ error: 'Could not read intake sheet', detail: intake });
    if (master.error || !master.columns) return res.status(502).json({ error: 'Could not read master sheet', detail: master });

    const I = resolve(intake, INTAKE_TITLES);
    const M = resolve(master, MASTER_TITLES);
    if (!I.groupId) return res.status(500).json({ error: 'Could not find a "Group ID" column on the intake sheet' });
    if (!M.groupId) return res.status(500).json({ error: 'Could not find a "GROUP ID" column on the master sheet' });

    // Group IDs already on the master
    const masterIds = new Set();
    let lastMasterRowId = null;
    for (const row of master.rows) {
      const gid = norm(cellVal(row, M.groupId));
      if (gid) { masterIds.add(gid.toLowerCase()); lastMasterRowId = row.id; }
    }

    // Master rows mirrored by the form BEFORE the intake formula generated their
    // Group ID: company filled, GROUP ID blank. Creating a fresh row for the
    // "missing" Group ID would put the group on the master twice (mirror row +
    // ours) — that was the doubling. Instead we ADOPT the blank mirror row:
    // write the Group ID onto it rather than inserting a new row.
    const blankRows = [];
    for (const row of master.rows) {
      if (norm(cellVal(row, M.groupId))) continue;
      const co = norm(cellVal(row, M.company));
      if (co) blankRows.push({ rowId: row.id, company: co.toLowerCase(), used: false });
    }

    // Intake rows missing from the master
    const missing = [];
    const adopt = [];
    const noGroupId = [];
    const batchSeen = new Set();   // within-batch guard: same gid twice in intake
    const tickIds = [];            // intake rows to tick 'Synced to Master' (on commit)
    const gidToIntakeRow = new Map();
    for (const row of intake.rows) {
      const gid = norm(cellVal(row, I.groupId));
      const company = norm(cellVal(row, I.company));
      if (!gid) { if (company) noGroupId.push({ company, contact: norm(cellVal(row, I.contactName)) }); continue; }
      // Placeholder "IDs" (e.g. "Quote Only" on quote requests) are not real
      // groups — never sync them, or deleted rows keep resurrecting daily.
      if (/^(quote only|quote|n\/?a|tbd|none|pending|test)$/i.test(gid)) continue;
      // Retired/archived groups: a "Do Not Sync" checkbox on the intake row lets
      // a real group be permanently removed from the master without it getting
      // re-created on the next run (e.g. VQ9GREDJUL26 / Red8 kept resurrecting
      // after being archived). Check the box on the intake row to retire a group.
      if (I.doNotSync) { const v = cellVal(row, I.doNotSync); if (v === true || /^(true|1|yes|y)$/i.test(norm(v))) continue; }
      if (I.synced && cellVal(row, I.synced) === true) continue;   // already synced once: never re-create
      if (masterIds.has(gid.toLowerCase())) { if (I.synced) tickIds.push(row.id); continue; }
      if (batchSeen.has(gid.toLowerCase())) continue;
      batchSeen.add(gid.toLowerCase());
      gidToIntakeRow.set(gid, row.id);
      const blank = blankRows.find(b => !b.used && b.company === company.toLowerCase());
      if (blank) { blank.used = true; adopt.push({ rowId: blank.rowId, groupId: gid, company }); continue; }
      missing.push({
        groupId: gid,
        company,
        contactName:  norm(cellVal(row, I.contactName)),
        contactEmail: norm(cellVal(row, I.contactEmail)),
        contactPhone: norm(cellVal(row, I.contactPhone)),
        startDate:    norm(cellVal(row, I.startDate)),
        endDate:      norm(cellVal(row, I.endDate)),
      });
    }

    if (!commit) {
      return res.status(200).json({
        dryRun: true,
        ...heal,
        intakeRows: intake.rows.length,
        masterGroups: masterIds.size,
        missingFromMaster: missing.length,
        missing,
        blankRowsToAdopt: adopt.length,
        adopt,
        intakeRowsWithNoGroupId: noGroupId.length,
        noGroupId,
        syncedColumn: !!I.synced,
        note: I.synced ? 'Nothing was written. Re-run with ?commit=1 to create the missing master rows.' : 'No "Synced to Master" column on intake yet: run ?setup=1&commit=1 FIRST or archived groups will be re-created.',
      });
    }

    const tick = async ids => {
      if (!I.synced || !ids.length) return;
      for (let i = 0; i < ids.length; i += 100) {
        await api(`/sheets/${INTAKE_SHEET}/rows`, { method: 'PUT', body: JSON.stringify(ids.slice(i, i + 100).map(id => ({ id, cells: [{ columnId: I.synced, value: true }] }))) });
      }
    };
    await tick(tickIds);                                          // groups already on the master
    await tick(adopt.map(a => gidToIntakeRow.get(a.groupId)).filter(Boolean));

    // Adopt blank mirror rows first: fill their Group ID in place (no new row).
    if (adopt.length) {
      const fixRows = adopt.map(a => ({
        id: a.rowId,
        cells: [
          { columnId: M.groupId, value: a.groupId },
          ...(M.autoSynced ? [{ columnId: M.autoSynced, value: true }] : []),
        ],
      }));
      await api(`/sheets/${MASTER_SHEET}/rows`, { method: 'PUT', body: JSON.stringify(fixRows) });
    }

    if (missing.length === 0) return res.status(200).json({ committed: true, created: 0, adopted: adopt.length, ...heal, message: adopt.length ? `Adopted ${adopt.length} blank mirror row(s); nothing else missing.` : 'Master already has every intake group.' });

    const newRows = missing.map(g => {
      const cells = [
        { columnId: M.groupId,    value: g.groupId },
        { columnId: M.company,    value: g.company },
        { columnId: M.contactName,value: g.contactName },
        { columnId: M.contactEmail,value: g.contactEmail },
        { columnId: M.contactPhone,value: g.contactPhone },
      ];
      if (M.status)    cells.push({ columnId: M.status, value: 'New' });
      if (M.completed) cells.push({ columnId: M.completed, value: false });
      if (M.startDate && g.startDate) cells.push({ columnId: M.startDate, value: g.startDate });
      if (M.endDate && g.endDate)     cells.push({ columnId: M.endDate, value: g.endDate });
      if (M.autoSynced) cells.push({ columnId: M.autoSynced, value: true });
      const def = { cells: cells.filter(c => c.value !== '' && c.value != null) };
      if (lastMasterRowId) def.siblingId = lastMasterRowId; else def.toBottom = true;
      return def;
    });

    const result = await api(`/sheets/${MASTER_SHEET}/rows`, { method: 'POST', body: JSON.stringify(newRows) });
    if (result.message && result.message !== 'SUCCESS') {
      return res.status(502).json({ committed: false, error: result.message, detail: result });
    }
    await tick(missing.map(m => gidToIntakeRow.get(m.groupId)).filter(Boolean));
    return res.status(200).json({
      committed: true,
      created: missing.length,
      adopted: adopt.length,
      groups: missing.map(m => m.groupId),
      message: `Created ${missing.length} missing master row(s)${adopt.length ? `, adopted ${adopt.length} blank mirror row(s)` : ''}.`,
    });
  } catch (err) {
    return res.status(500).json({ error: err.message });
  }
}
