// Reconcile: Group Travel intake sheet  →  LIVE GROUP MASTERSHEET
//
// Why this exists: the website form (/api/submit) mirrors a submission to the
// master at submission time, but the GROUP ID is generated by a Smartsheet
// formula on the intake sheet AFTER the row lands — so the form can't carry it.
// The master's Group IDs are populated by a separate automation; if that
// automation ever misses a row (as happened with Monster Energy / VQ9GMONAUG26),
// the group is in the intake sheet but never reaches the master.
//
// This endpoint closes that gap: it lists every intake group that isn't in the
// master and (on commit) creates it. Columns are resolved BY TITLE on both
// sheets so a column-ID change can never write to the wrong field.
//
// Usage (on Vercel, where SMARTSHEET_API_TOKEN is set):
//   GET /api/reconcile-groups            → DRY RUN: reports what's missing, writes nothing
//   GET /api/reconcile-groups?commit=1   → creates the missing master rows

const INTAKE_SHEET = '3569349083221892';   // Group Travel intake sheet
const MASTER_SHEET = '4820086761148292';   // LIVE GROUP MASTERSHEET

// candidate titles (case-insensitive) for each logical field, per sheet
const INTAKE_TITLES = {
  groupId:      ['Group ID'],
  company:      ['Company Name'],
  contactName:  ['Event Manager / Contact Name', 'Event Manager/Contact Name', 'Contact Name', 'Event Manager'],
  contactEmail: ['Event Manager Email', 'Event Manager E-mail', 'Contact Email', 'Contact E-mail'],
  contactPhone: ['Event Manager Contact Number', 'Event Manager Phone', 'Contact Phone', 'Contact Number'],
  startDate:    ['Arrival Date', 'Travel Start Date', 'Start Date'],
  endDate:      ['Departure Date', 'Travel End Date', 'End Date'],
};
const MASTER_TITLES = {
  groupId:      ['GROUP ID', 'Group ID'],
  company:      ['Company Name'],
  contactName:  ['Contact Name'],
  contactEmail: ['Contact E-mail', 'Contact Email'],
  contactPhone: ['Contact Phone', 'Contact Number'],
  status:       ['Status'],
  completed:    ['Completed'],
  startDate:    ['Travel Start Date', 'Start Date'],
  endDate:      ['Travel End Date', 'End Date'],
  autoSynced:   ['Auto-Synced', 'Auto Synced'],
};

export default async function handler(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
  if (req.method === 'OPTIONS') return res.status(200).end();

  const TOKEN = process.env.SMARTSHEET_API_TOKEN;
  if (!TOKEN) return res.status(500).json({ error: 'Missing SMARTSHEET_API_TOKEN' });
  const commit = req.query?.commit === '1' || req.body?.commit === true;

  const api = (path, opts = {}) =>
    fetch(`https://api.smartsheet.com/2.0${path}`, {
      ...opts,
      headers: { Authorization: `Bearer ${TOKEN}`, 'Content-Type': 'application/json', ...opts.headers },
    }).then(r => r.json());

  const ZWSP = /​/g;
  const norm = v => (v == null ? '' : String(v)).replace(ZWSP, '').trim();
  const cellVal = (row, colId) => {
    const c = row.cells?.find(c => c.columnId === colId);
    return c?.value ?? c?.displayValue ?? null;
  };
  const resolve = (sheet, titleMap) => {
    const byTitle = {};
    for (const c of sheet.columns) byTitle[c.title.trim().toLowerCase()] = c.id;
    const out = {};
    for (const [field, candidates] of Object.entries(titleMap)) {
      for (const t of candidates) { const id = byTitle[t.trim().toLowerCase()]; if (id) { out[field] = id; break; } }
    }
    return out;
  };

  // ── Status self-heal (Vera 2026-07-08) ────────────────────────────────────
  // The GROUPS dashboard report only shows rows that have a Status; manually
  // added groups arrive with a blank one and silently vanish from the widget.
  // Fix: any master row with a GROUP ID but no Status gets 'New'. Runs (a)
  // instantly via a Smartsheet webhook on the master (register once with
  // ?registerHook=1), (b) on the daily cron, (c) on any manual run.
  async function backfillStatus() {
    const master = await api(`/sheets/${MASTER_SHEET}`);
    if (master.error || !master.columns) return { backfillError: 'could not read master' };
    const M = resolve(master, MASTER_TITLES);
    if (!M.groupId || !M.status) return { backfillError: 'missing GROUP ID / Status column' };
    const fixes = (master.rows || [])
      .filter(r => norm(cellVal(r, M.groupId)) && !norm(cellVal(r, M.status)))
      .map(r => ({ id: r.id, cells: [{ columnId: M.status, value: 'New' }] }));
    if (fixes.length) await api(`/sheets/${MASTER_SHEET}/rows`, { method: 'PUT', body: JSON.stringify(fixes) });
    return { statusBackfilled: fixes.length };
  }

  // Smartsheet webhook verification challenge — echo it.
  const hookChallenge = req.headers['smartsheet-hook-challenge'];
  if (hookChallenge) {
    res.setHeader('Smartsheet-Hook-Response', hookChallenge);
    return res.status(200).json({ smartsheetHookResponse: hookChallenge });
  }

  // Smartsheet webhook change event on the master → self-heal right now.
  // (The backfill's own PUT re-fires the webhook once; the second pass finds
  // nothing blank and writes nothing, so it converges immediately.)
  const pbody = typeof req.body === 'string' ? (() => { try { return JSON.parse(req.body); } catch { return {}; } })() : (req.body || {});
  if (req.method === 'POST' && Array.isArray(pbody.events)) {
    const out = await backfillStatus();
    return res.status(200).json({ ok: true, ...out });
  }

  // One-time self-registration of that webhook: GET ?registerHook=1
  if (req.query?.registerHook === '1') {
    const hooks = await api(`/webhooks?includeAll=true`);
    let hook = (hooks.data || []).find(h => String(h.scopeObjectId) === MASTER_SHEET && (h.callbackUrl || '').includes('/api/reconcile-groups'));
    if (!hook) {
      const cr = await api(`/webhooks`, { method: 'POST', body: JSON.stringify({ name: 'Groups status self-heal', callbackUrl: 'https://kensington-group-form.vercel.app/api/reconcile-groups', scope: 'sheet', scopeObjectId: Number(MASTER_SHEET), events: ['*.*'], version: 1 }) });
      hook = cr.result;
      if (!hook) return res.status(502).json({ error: 'webhook create failed', detail: cr });
    }
    const en = hook.enabled ? { result: hook } : await api(`/webhooks/${hook.id}`, { method: 'PUT', body: JSON.stringify({ enabled: true }) });
    const bf = await backfillStatus();
    return res.status(200).json({ ok: true, webhook: { id: hook.id, enabled: en.result?.enabled ?? hook.enabled, status: en.result?.status ?? hook.status }, ...bf });
  }

  try {
    const heal = await backfillStatus();
    const [intake, master] = await Promise.all([api(`/sheets/${INTAKE_SHEET}`), api(`/sheets/${MASTER_SHEET}`)]);
    if (intake.error || !intake.columns) return res.status(502).json({ error: 'Could not read intake sheet', detail: intake });
    if (master.error || !master.columns) return res.status(502).json({ error: 'Could not read master sheet', detail: master });

    const I = resolve(intake, INTAKE_TITLES);
    const M = resolve(master, MASTER_TITLES);
    if (!I.groupId) return res.status(500).json({ error: 'Could not find a "Group ID" column on the intake sheet' });
    if (!M.groupId) return res.status(500).json({ error: 'Could not find a "GROUP ID" column on the master sheet' });

    // Group IDs already on the master
    const masterIds = new Set();
    let lastMasterRowId = null;
    for (const row of master.rows) {
      const gid = norm(cellVal(row, M.groupId));
      if (gid) { masterIds.add(gid.toLowerCase()); lastMasterRowId = row.id; }
    }

    // Intake rows missing from the master
    const missing = [];
    const noGroupId = [];
    for (const row of intake.rows) {
      const gid = norm(cellVal(row, I.groupId));
      const company = norm(cellVal(row, I.company));
      if (!gid) { if (company) noGroupId.push({ company, contact: norm(cellVal(row, I.contactName)) }); continue; }
      if (masterIds.has(gid.toLowerCase())) continue;
      missing.push({
        groupId: gid,
        company,
        contactName:  norm(cellVal(row, I.contactName)),
        contactEmail: norm(cellVal(row, I.contactEmail)),
        contactPhone: norm(cellVal(row, I.contactPhone)),
        startDate:    norm(cellVal(row, I.startDate)),
        endDate:      norm(cellVal(row, I.endDate)),
      });
    }

    if (!commit) {
      return res.status(200).json({
        dryRun: true,
        ...heal,
        intakeRows: intake.rows.length,
        masterGroups: masterIds.size,
        missingFromMaster: missing.length,
        missing,
        intakeRowsWithNoGroupId: noGroupId.length,
        noGroupId,
        note: 'Nothing was written. Re-run with ?commit=1 to create the missing master rows.',
      });
    }

    if (missing.length === 0) return res.status(200).json({ committed: true, created: 0, ...heal, message: 'Master already has every intake group.' });

    const newRows = missing.map(g => {
      const cells = [
        { columnId: M.groupId,    value: g.groupId },
        { columnId: M.company,    value: g.company },
        { columnId: M.contactName,value: g.contactName },
        { columnId: M.contactEmail,value: g.contactEmail },
        { columnId: M.contactPhone,value: g.contactPhone },
      ];
      if (M.status)    cells.push({ columnId: M.status, value: 'New' });
      if (M.completed) cells.push({ columnId: M.completed, value: false });
      if (M.startDate && g.startDate) cells.push({ columnId: M.startDate, value: g.startDate });
      if (M.endDate && g.endDate)     cells.push({ columnId: M.endDate, value: g.endDate });
      if (M.autoSynced) cells.push({ columnId: M.autoSynced, value: true });
      const def = { cells: cells.filter(c => c.value !== '' && c.value != null) };
      if (lastMasterRowId) def.siblingId = lastMasterRowId; else def.toBottom = true;
      return def;
    });

    const result = await api(`/sheets/${MASTER_SHEET}/rows`, { method: 'POST', body: JSON.stringify(newRows) });
    if (result.message && result.message !== 'SUCCESS') {
      return res.status(502).json({ committed: false, error: result.message, detail: result });
    }
    return res.status(200).json({
      committed: true,
      created: missing.length,
      groups: missing.map(m => m.groupId),
      message: `Created ${missing.length} missing master row(s).`,
    });
  } catch (err) {
    return res.status(500).json({ error: err.message });
  }
}
